# Here you can set different frequencies in order to generate synthetic data based on them
# add '-' if this probability should not be considered

WEEKS_NUM: 30 # instead of dates, just num of weeks
users_number: 10000 #this will be approximate number of user by END_DATE
artists_number: 1000

frequencies_genre: {
  'Pop': {
    "user": 400,
    "artist": 300
  },
  'Rock': {
    "user": 700,
    "artist": 200
  },
  'Hip-hop': {
    "user": 300,
    "artist": 100
  },
  'Electronic': {
    "user": 200,
    "artist": 200
  },
  'Jazz': {
    "user": 170,
    "artist": 500
  },
  'Classical': {
    "user": 100,
    "artist": 100
  },
  'Blues': {
    "user": 150,
    "artist": 300
  },
  'Alternative': {
    "user": 400,
    "artist": 400
  },
}

"frequencies_continent": {
  'North America': {
    "user": 700,
    "artist": 700,
  },
  'South America': {
    "user": 400,
    "artist": 400,
  },
  'Europe': {
    "user": 500,
    "artist": 500,
  },
  'Africa': {
    "user": 200,
    "artist": 200,
  },
  'Asia': {
    "user": 300,
    "artist": 300,
  },
  'Oceana': {
    "user": 100,
    "artist": 100,
  },
}


min_streams_to_favorites: 7 #minimum of listens to song before adding to favorite
min_streams_to_famous_song: 1000 #minimum streams to song before becoming famous
min_streams_to_famous_artist: 20000 #minimum streams to song before becoming famous


#Number of STREAMS
avg_songs_unsub: 20 #average songs listened by unsubscribed users in a week
avg_songs_sub: 50 #average songs listened by subscribed users in a week

# Probabilities
#Random songs section
p_random_songs_stream: 0.6 #probability that user will access random songs section
p_favorite_playlist: 0.8 #probability that user will access favorite songs section


p_fav_art_sng_gnr_cnt: 0.8 #Probability of listening to song with famous artist, famous song, favorite genre, same continent
p_fav_art_sng_gnr: 0.7 #Probability of listening to song with famous artist, famous song, favorite genre
p_fav_gnr: 0.6 #Probability of listening to favorite genre
p_other: 0.4 #other



p_favorite: 0.6 # probability that user will listen to song that is a favorite



