# Here you can set different frequencies in order to generate synthetic data based on them

#change artist, premium, user_subscribed

WEEKS_NUM: 15 # instead of dates, just num of weeks
users_rate: 8000 #this will be approximate number of user by END_DATE
artists_rate: 8000

frequencies_genre: {
  'Pop': {
    "user": 0,
    "artist": 0
  },
  'Rock': {
    "user": 200,
    "artist": 0
  },
  'Hip-hop': {
    "user": 500,
    "artist": 00
  },
  'Electronic': {
    "user": 0,
    "artist": 00
  },
  'Jazz': {
    "user": 50,
    "artist": 50
  },
  'Classical': {
    "user": 00,
    "artist": 0
  },
  'Blues': {
    "user": 0,
    "artist": 0
  },
  'Alternative': {
    "user": 0,
    "artist": 450
  },
}

"frequencies_continent": {
  'North America': {
    "user": 0,
    "artist": 0,
  },
  'South America': {
    "user": 00,
    "artist": 00,
  },
  'Europe': {
    "user": 300,
    "artist": 300,
  },
  'Africa': {
    "user": 00,
    "artist": 00,
  },
  'Asia': {
    "user": 0,
    "artist": 0,
  },
  'Oceana': {
    "user": 0,
    "artist": 0,
  },
}


min_streams_to_favorites: 500 #minimum of listens to song before adding to favorite
min_streams_to_famous_song: 500 #minimum streams to song before becoming famous
min_streams_to_famous_artist: 500 #minimum streams to song before becoming famous


#Number of STREAMS
avg_songs_unsub: 400 #average songs listened by unsubscribed users in a week
avg_songs_sub: 400 #average songs listened by subscribed users in a week

# Probabilities
#Random songs section
p_random_songs_stream: 1 #probability that user will access random songs section
p_favorite_playlist: 1 #probability that user will access favorite songs section


p_fav_art_sng_gnr_cnt: 1 #Probability of listening to song with famous artist, famous song, favorite genre, same continent
p_fav_art_sng_gnr: 1 #Probability of listening to song with famous artist, famous song, favorite genre
p_fav_gnr: 1 #Probability of listening to favorite genre
p_other: 1 #other



p_favorite: 1 # probability that user will listen to song that is a favorite


